DjangoProgress/urls.py
# Django libs:
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# Our libs:
from DjangoProgress import settings


# URL patterns:
urlpatterns = [
    # Admin view:
    path('admin/', admin.site.urls),

    # Main:
    path('', TemplateView.as_view(template_name="main_index.html"), name="main_index"),
]

# Apps:
for app in settings.EXTRA_APPS:
    urlpatterns.append(path(f'{app}/', include(f'{app}.urls', namespace=app)))

books/urls.py
# Django libs:
from django.urls import path

# Our libs:
from books import views


# Constants:
app_name = "books"


# URL patterns:
urlpatterns = [
    # Main:
    path('', views.stats, name="stats"),

    # Misc:
    path('index', views.index, name="index"),
    path('sagas', views.sagas, name="sagas"),
    path('stats/<int:year>', views.stats, name="stats"),

    # Details:
    path('book/<int:book_id>', views.book_detail, name='book_detail'),
    path('author/<int:author_id>', views.author_detail, name='author_detail'),

    # Forms:
    path('add_book', views.add_book, name='add_book'),
    path('modify_book/<int:book_id>', views.modify_book, name='modify_book'),
    path('start_book', views.start_book, name='start_book'),
    path('update_book_progress/<int:book_id>', views.update_book_progress, name='update_book_progress'),
    path('mark_book_read/<int:book_id>', views.mark_book_read, name='mark_book_read'),
    path('mark_book_owned/<int:book_id>', views.mark_book_owned, name='mark_book_owned'),
]

gasolina/urls.py
# Django libs:
from django.urls import path

# Our web libs:
from . import views


# Constants:
app_name = "gasolina"


# URL definitions:
urlpatterns = [
    # Index:
    path('', views.index, name='index'),

    # Single plots:
    path('plot/<item>', views.plot_item, name='plot_item'),

    # Data URLs:
    path('item_data/<item>', views.item_data, name='item_data'),
]

gasolina/models.py
from django.db import models
from django.utils import timezone


class PlotState(models.Model):
    """The values of all plot variables."""

    # Attributes:
    timestamp = models.DateTimeField("Timestamp", default=timezone.now)
    total_kms = models.IntegerField("Total kilometres", default=0)
    partial_kms = models.FloatField("Partial kilometres", default=0)
    litres = models.FloatField("Litres", default=0)
    price = models.FloatField("Price (eur/L)", default=0)
    
    # Special functions:
    def __str__(self):
        return "{s.timestamp}".format(s=self)

    def __unicode__(self):
        return self.__str__()


class VariableConfig(models.Model):
    """The configuration parameters for a variable."""

    # Attributes:
    name = models.CharField("Name", default="name", max_length=50)
    long_name = models.CharField("Long name", default="long_name", max_length=100)
    style = models.CharField("Plot style", default="r", max_length=50)
    objective = models.IntegerField("Objective", default=1)

    # Special functions:
    def __str__(self):
        return self.long_name

    def __unicode__(self):
        return self.__str__()

gasolina/forms.py
from django import forms

class VsTimeForm(forms.Form):
    timestamp = forms.CharField(label="Date", max_length=10)
    total_kms = forms.IntegerField(label="Total kms")
    partial_kms = forms.FloatField(label="Partial kms")
    litres = forms.FloatField(label="Litres consumed")
    price = forms.FloatField(label="Price (eur/L)")

gasolina/views.py
# Standard libs:
from datetime import datetime

# Django libs:
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Our libs:
from gasolina.forms import VsTimeForm
from gasolina.models import PlotState, VariableConfig


# Indices:
def index(request):
    """Show stats historically."""

    if request.method == "POST":
        form = VsTimeForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            # Create Stats object:
            ps = PlotState()
            ps.timestamp = datetime.strptime(data["timestamp"], "%Y-%m-%d")
            ps.timestamp = ps.timestamp.replace(hour=12)
            ps.total_kms = data["total_kms"]
            ps.partial_kms = data["partial_kms"]
            ps.litres = data["litres"]
            ps.price = data["price"]
            ps.save()

        # Back to stats_vs_time:
        return redirect("gasolina:index")

    else:
        if PlotState.objects.all():
            ps = PlotState.objects.order_by("-timestamp")[0]
            initial = {
                "timestamp": datetime.now().strftime("%Y-%m-%d"),
                "total_kms": ps.total_kms,
                "partial_kms": ps.partial_kms,
                "litres": ps.litres,
                "price": ps.price
            }
            timestamp = ps.timestamp
        else:
            initial = {}
            timestamp = datetime.utcnow()

        context = {
            "form": VsTimeForm(initial=initial),
            "timestamp": timestamp,
            "item": "intake",
        }

        return render(request, 'gasolina/index.html', context)


# Plots:
def plot_item(request, item):
    """Plot a single item history."""

    context = {
        "item": item,
    }
    
    return render(request, 'gasolina/plot_item.html'.format(i=item), context)


# Data URLs:
def item_data(request, item):
    """Return JSON with intake data to be plotted."""

    color_of = {
        "intake": "#cc0000",
        "range": "#00cc00",
        "kms_per_year": "#00cccc",
        "euros_per_month": "#cc0000",
    }

    data = {
        "data": data_to_plot(item),
        "color": color_of[item],
        "label": item,
        "xlabel": "mierder",
    }

    return JsonResponse(data)


# Utility functions:
def data_to_plot(item):
    """Return dictionary with data corresponding to 'item'."""
    
    data_objects = PlotState.objects.order_by("timestamp")

    # Choose data:
    if item == "intake":
        x_axis = [d.total_kms for d in data_objects[1:]]
        y_axis = [100*d.litres/d.partial_kms for d in data_objects[1:]]

    elif item == "range":
        y_axis = [d.partial_kms for d in data_objects[1:]]
        x_axis = range(len(y_axis))

    elif item == "kms_per_year":
        date0 = data_objects[0].timestamp
        days = [(d.timestamp - date0).total_seconds()/86400. for d in data_objects[1:]] # days
        x_axis = [d.timestamp.strftime("%Y-%m-%d") for d in data_objects[1:]]
        y_axis = [365*d.total_kms/dt for d, dt in zip(data_objects[1:], days)]

    elif item == "euros_per_month":
        date0 = data_objects[0].timestamp
        x_axis = [d.timestamp.strftime("%Y-%m-%d") for d in data_objects[1:]]

        y_axis = []
        gastado = 0
        for datum in data_objects[1:]:
            gastado += datum.litres * datum.price # euros gastados repostando
            epm = 30*86400*gastado/(datum.timestamp - date0).total_seconds()
            y_axis.append(epm)

    # Build data object:
    data_dict = [{"x": x, "y": y} for x, y in zip(x_axis, y_axis)]

    return data_dict

gasolina/templates/gasolina/header.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}

<style>
    input { font-size: 200%; }
    label { font-size: 200%; }
</style>

<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.3/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'gasolina/style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'gasolina/icons/favicon.png' %}" />
</head>

<body>

<div class="top-buttons-grid" style="width: 100%">
    <a class="button-books" href="/">Home</a>
    <a class="button-books" href="{% url 'gasolina:index' %}">Gas</a>
    <a class="button-books" href="{% url 'gasolina:plot_item' 'intake' %}">Intake</a>
    <a class="button-books" href="{% url 'gasolina:plot_item' 'range' %}">Range</a>
    <a class="button-books" href="{% url 'gasolina:plot_item' 'kms_per_year' %}">km/year</a>
    <a class="button-books" href="{% url 'gasolina:plot_item' 'euros_per_month' %}">eur/month</a>
</div>

{% block content %}
{% endblock %}

</body>

gasolina/templates/gasolina/index.html
{% extends "gasolina/header.html" %}
{% load bootstrap4 %}

{% block content %}

<table width="50%">
    <tr>
        <td>
            <table>
                <tr>
                    <form method="POST" id="post-form" class="form">
                        {% csrf_token %}
                        {% bootstrap_form form layout="vertical" %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        {% endbuttons %}
                    </form>
                </tr>
            </table>
        </td>
    </tr>
</table>

{% endblock %}

gasolina/templates/gasolina/plot_item.html
{% load staticfiles %}

{% include "gasolina/header.html" %}

<div style="width: 100%; padding: 5 5; margin: auto auto;">
    <canvas id="item_chart"></canvas>
</div>

<meta id="data-url" data-name="{% url 'gasolina:item_data' item %}">

{% with "gasolina/js/"|add:item|add:".js" as chartjs %}
    <script src="{% static chartjs %}"></script>
{% endwith %}