DjangoProgress/urls.py
# Django libs:
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# Our libs:
from DjangoProgress import settings


# URL patterns:
urlpatterns = [
    # Admin view:
    path('admin/', admin.site.urls),

    # Main:
    path('', TemplateView.as_view(template_name="main_index.html"), name="main_index"),
]

# Apps:
for app in settings.EXTRA_APPS:
    urlpatterns.append(path(f'{app}/', include(f'{app}.urls', namespace=app)))

ahorro/urls.py
# Django libs:
from django.urls import path

# Our web libs:
from . import views


# Constants:
app_name = "ahorro"


# URL patterns:
urlpatterns = [
    # Index:
    path('', views.index, name='index'),

    # Single plots:
    path('plot/<item>', views.plot_item, name='plot_item'),

    # Data URLs:
    path('item_data/<item>', views.item_data, name='item_data'),
]

books/urls.py
# Django libs:
from django.urls import path

# Our libs:
from books import views


# Constants:
app_name = "books"


# URL patterns:
urlpatterns = [
    # Main:
    path('', views.stats, name="stats"),

    # Misc:
    path('index', views.index, name="index"),
    path('sagas', views.sagas, name="sagas"),
    path('stats/<int:year>', views.stats, name="stats"),

    # Details:
    path('book/<int:book_id>', views.book_detail, name='book_detail'),
    path('author/<int:author_id>', views.author_detail, name='author_detail'),

    # Forms:
    path('add_book', views.add_book, name='add_book'),
    path('modify_book/<int:book_id>', views.modify_book, name='modify_book'),
    path('start_book', views.start_book, name='start_book'),
    path('update_book_progress/<int:book_id>', views.update_book_progress, name='update_book_progress'),
    path('mark_book_read/<int:book_id>', views.mark_book_read, name='mark_book_read'),
    path('mark_book_owned/<int:book_id>', views.mark_book_owned, name='mark_book_owned'),
]

ahorro/models.py
# Django libs:
from django.db import models
from django.utils import timezone


# Classes:
class TimeInstant(models.Model):
    """A datetime, an instant in time."""

    timestamp = models.DateTimeField("Timestamp", default=timezone.now)

    # Public properties:
    @property
    def total_amount(self):
        """Sum of all amounts that have this TimeInstant as timestamp."""

        return sum([a.value for a in Amount.objects.filter(when=self)])

    # Special methods:
    def __unicode__(self):
        return self.__str__()

    def __str__(self):
        return self.timestamp.strftime("%Y-%m-%d %H:%M:%S")


class Account(models.Model):
    """The configuration parameters for an account."""

    name = models.CharField("Name", default="name", max_length=50)
    color = models.CharField("Color", default="#000000", max_length=7)
    icon = models.CharField("Icon", default="default.png", max_length=100)

    # Special methods:
    def __unicode__(self):
        return self.__str__()

    def __str__(self):
        return self.name


class Amount(models.Model):
    """An amount of money (for a given Account, on a given TimeInstant)."""

    value = models.FloatField("Amount", default=0.0)
    when = models.ForeignKey(TimeInstant, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    # Special methods:
    def __unicode__(self):
        return self.__str__()

    def __str__(self):
        return "{s.value:.2f} eur for {s.account} at {s.when}".format(s=self)

ahorro/forms.py
# Django libs:
from django import forms

# Our libs:
from ahorro.models import Account

# Classes:
class AmountForm(forms.Form):
    timestamp = forms.CharField(label="Date", max_length=10)
    #total_kms = forms.IntegerField(label="Total kms")
    #partial_kms = forms.FloatField(label="Partial kms")

    def __init__(self, *args, **kwargs):
        super(AmountForm, self).__init__(*args, **kwargs)

        for account in Account.objects.all():
            self.fields[account.name] = forms.FloatField(label=account.name)

ahorro/views.py
# Standard libs:
from datetime import datetime

# Django libs:
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Our libs:
from ahorro.forms import AmountForm
from ahorro.models import Amount, TimeInstant, Account


# Index views:
def index(request):
    """Show index."""

    if request.method == "POST":
        form = AmountForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            
            # Create TimeInstant entry:
            ti = TimeInstant()
            ti.timestamp = datetime.strptime(data["timestamp"], "%Y-%m-%d")
            ti.timestamp = ti.timestamp.replace(hour=12)
            ti.save()

            # Create Amount entries:
            for field, value in data.items():
                if field == "timestamp":
                    continue

                amount = Amount()
                amount.value = value
                amount.account = Account.objects.get(name=field)
                amount.when = ti
                amount.save()

        # Back to stats_vs_time:
        return redirect("ahorro:index")

    else:
        timestamp = datetime.now().strftime("%Y-%m-%d")
        initial = {
            "timestamp": timestamp,
        }
        for account in Account.objects.all():
            initial[account.name] = 0.0

        context = {
            "form": AmountForm(initial=initial),
            "account_list": [a for a in Account.objects.all()],
        }

        return render(request, 'ahorro/index.html', context)


# Plots:
def plot_item(request, item):
    """Plot a single item history."""

    context = {
        "item": item,
        "account_list": [a for a in Account.objects.all()],
    }
    
    return render(request, 'ahorro/plot_item.html'.format(i=item), context)


# Data URLs:
def data_to_plot(item):
    """Return dictionary with data corresponding to 'item'."""
    
    #data_objects = PlotState.objects.order_by("timestamp")
    x_axis,  y_axis = [], []

    # Choose data:
    if item == "total":
        time_amount = [(ti.timestamp, ti.total_amount) for ti in TimeInstant.objects.order_by("timestamp")]
        xy_axes = [(t.strftime("%Y-%m-%d %H:%M"), a) for t, a in time_amount]

    else:
        amounts = Amount.objects.filter(account__name=item).order_by("when")
        xy_axes = [(a.when.timestamp.strftime("%Y-%m-%d %H:%M"), a.value) for a in amounts]


    # Build data object:
    data_dict = [{"x": x, "y": y} for x, y in xy_axes]

    return data_dict

def item_data(request, item):
    """Return JSON with item data to be plotted."""

    if item == "total":
        color = "#00cc00"
    else:
        color = Account.objects.get(name=item).color

    data = {
        "data": data_to_plot(item),
        "color": color,
        "label": item,
    }
    
    return JsonResponse(data)

ahorro/templates/ahorro/header.html
{% load static %}
{% load bootstrap3 %}
{% bootstrap_css %}

<style>
    input { font-size: 200%; }
    label { font-size: 200%; }
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.3/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="{% static 'ahorro/style.css' %}" />
<link rel="shortcut icon" type="image/png" href="{% static 'ahorro/icons/favicon.png' %}" />

<table>
    <tr>
      <td><a href="/"><img src="{% static 'ahorro/icons/home.png' %}" alt="default" style="width: 64px;" /></a></td>
      <td><a href="{% url 'ahorro:index' %}">
          <img src="{% static 'ahorro/icons/ahorro_logo.png' %}" alt="default" style="width: 64px;" /></a>
      </td>
      <td><a href="{% url 'ahorro:plot_item' 'total' %}">
          <img src="{% static 'ahorro/icons/Euros-512.png' %}" alt="default" style="width: 64px;" /></a>
      </td>
      {% for account in account_list %}
      <td>
          <a href="{% url 'ahorro:plot_item' account.name %}">
              {% with "ahorro/icons/"|add:account.icon as acc_icon %}
                  <img src="{% static acc_icon %}" alt="{{account.name}}" style="width: 64px;" /></a>
              {% endwith %}
      </td>
      {% endfor %}
    </tr>
</table>

{% block content %}
{% endblock %}

ahorro/templates/ahorro/index.html
{% extends "ahorro/header.html" %}
{% load bootstrap3 %}

{% block content %}
<table width="50%">
    <tr>
        <td>
            <table>
                <tr>
                    <form method="POST" id="post-form" class="form">
                        {% csrf_token %}
                        {% bootstrap_form form layout="vertical" %}
                        {% buttons %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                        {% endbuttons %}
                    </form>
                </tr>
            </table>
        </td>
    </tr>
</table>
{% endblock %}

ahorro/templates/ahorro/plot_item.html
{% extends "ahorro/header.html" %}

{% block content %}

{% load staticfiles %}

<div style="width: 90%; padding: 0 0; margin: auto auto;">
    <canvas id="item_chart"></canvas>
</div>

<meta id="data-url" data-name="{% url 'ahorro:item_data' item %}">

<script src="{% static 'ahorro/js/item_chart.js' %}"></script>

{% endblock %}