DjangoProgress/urls.py
# Django libs:
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# Our libs:
from DjangoProgress import settings


# URL patterns:
urlpatterns = [
    # Admin view:
    path('admin/', admin.site.urls),

    # Main:
    path('', TemplateView.as_view(template_name="main_index.html"), name="main_index"),
]

# Apps:
for app in settings.EXTRA_APPS:
    urlpatterns.append(path(f'{app}/', include(f'{app}.urls', namespace=app)))

books/urls.py
# Django libs:
from django.urls import path

# Our libs:
from books import views


# Constants:
app_name = "books"


# URL patterns:
urlpatterns = [
    # Main:
    path('', views.stats, name="stats"),

    # Misc:
    path('index', views.index, name="index"),
    path('sagas', views.sagas, name="sagas"),
    path('stats/<int:year>', views.stats, name="stats"),

    # Details:
    path('book/<int:book_id>', views.book_detail, name='book_detail'),
    path('author/<int:author_id>', views.author_detail, name='author_detail'),

    # Forms:
    path('add_book', views.add_book, name='add_book'),
    path('modify_book/<int:book_id>', views.modify_book, name='modify_book'),
    path('start_book', views.start_book, name='start_book'),
    path('update_book_progress/<int:book_id>', views.update_book_progress, name='update_book_progress'),
    path('mark_book_read/<int:book_id>', views.mark_book_read, name='mark_book_read'),
    path('mark_book_owned/<int:book_id>', views.mark_book_owned, name='mark_book_owned'),
]

books/forms.py
from django import forms


class BookForm(forms.Form):
    pages_read = forms.IntegerField(label="Pages read", max_value=10000, required=False)


class AddBookForm(forms.Form):
    title = forms.CharField(label="Title")
    author = forms.CharField(label="Author(s)")
    pages = forms.IntegerField(label="Pages")
    year = forms.IntegerField(label="Year")
    saga = forms.CharField(label="Saga", required=False)
    index = forms.CharField(label="Index in saga", required=False)


class SearchBookForm(forms.Form):
    search_for = forms.CharField(label="Search for")

books/views.py
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect

from . import core, statistics
from .models import Book, Author, BookStartEvent, Saga, BookEndEvent
from .forms import BookForm, AddBookForm, SearchBookForm


def index(request):
    """Index view."""

    context = {
        "currently_reading_books": currently_reading_books(),
        "currently_ordered_books": currently_ordered_books(),
        "already_read_books": already_read_books(),
    }

    return render(request, "books/index.html", context)


def sagas(request):
    """Saga view."""

    context = {
        "sagas": Saga.objects.all(),
        "completed": completed_sagas(),
        "owned": owned_sagas(),
        "missing": missing_sagas(),
    }

    return render(request, "books/sagas.html", context)


def book_detail(request, book_id):
    """Detail view for a book."""

    book = Book.objects.get(pk=book_id)

    reading = []  # list of (when, pages) for a time read
    readings = []  # one reading per time read
    for event in book.events:
        reading.append((event.when, event.page_equivalent))
        if event.page_equivalent == book.pages:
            readings.append(reading)
            reading = []
    if reading:
        readings.append(reading)

    # Longest reading:
    longest = None
    for reading in readings:
        dt = reading[-1][0] - reading[0][0]
        if longest is None or dt > longest:
            longest = dt

    context = {
        "book": book,
        "plotly_plots": [core.get_book_progress_plot(r, longest) for r in readings],
    }

    return render(request, "books/book_detail.html", context)


def update_book_progress(request, book_id):
    """Form to modify state of book."""

    book = Book.objects.get(pk=book_id)

    if request.method == "POST":
        form = BookForm(request.POST or None)
        if form.is_valid():
            pages_read = form.cleaned_data.get("pages_read")
            if pages_read is not None:
                if not book.is_currently_being_read:
                    book.mark_started()
                if pages_read > 0:
                    book.set_pages(pages_read)

                return redirect("books:book_detail", book_id=book_id)

    initial = {
        "pages_read": book.pages_read,
    }
    form = BookForm(initial=initial)

    context = {
        "form": form,
        "book": book,
    }

    return render(request, 'books/update_book_progress.html', context)


def add_book(request):
    """Form to add a new Book."""

    if request.method == "POST":
        form = AddBookForm(request.POST or None)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            if title is not None:
                # Add data:
                book = Book()
                book.title = title
                book.pages = form.cleaned_data.get("pages")
                book.year = form.cleaned_data.get("year")

                if "acquired" not in request.POST and "reading" not in request.POST:
                    book.owned = False

                if "ordered" in request.POST:
                    book.ordered = True

                # Saga info:
                saga_name = form.cleaned_data.get("saga")
                if saga_name:
                    try:
                        book.saga = Saga.objects.get(name=saga_name)
                    except ObjectDoesNotExist:
                        # Horrible hack to assign to new Saga object the first available id, because PostgreSQL
                        # at Heroku fails to assign an automatic one that is not duplicated if we simply do:
                        # saga = Saga(name=saga_name)
                        saga_id = 1
                        for saga_id in range(1, 10000):  # max try 10000 sagas
                            print("DEBUG105", saga_id)
                            if not Saga.objects.filter(id=saga_id):
                                break
                        saga = Saga(name=saga_name, id=saga_id)
                        saga.save()
                        book.saga = saga
                    book.index_in_saga = form.cleaned_data.get("index")
                book.save()  # we must save BEFORE we add many-to-many field items (author(s) below)

                # Add author data:
                author_names = [a.strip() for a in form.cleaned_data.get("author", "").split(",")]
                for author_name in author_names:
                    try:
                        author = Author.objects.get(name=author_name)
                    except Author.DoesNotExist:
                        author = Author(name=author_name)
                        author.save()
                    book.authors.add(author)

                # Add started reading:
                if "reading" in request.POST:
                    start = BookStartEvent()
                    start.book = book
                    start.when = timezone.now()
                    start.save()

                return redirect("books:book_detail", book_id=book.id)

    initial = {
        "pages": 0,
        "year": 0,
        "saga": None,
        "index": None,
    }
    form = AddBookForm(initial=initial)
    context = {
        "form": form,
        "action": "add",
    }

    return render(request, 'books/add_or_modify_book.html', context)


def modify_book(request, book_id=None):
    """Form to modify a Book."""

    if request.method == "POST":
        form = AddBookForm(request.POST or None)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            if title is not None:
                book = Book.objects.get(id=book_id)  # book to modify
                book.title = title
                book.pages = form.cleaned_data.get("pages")
                book.year = form.cleaned_data.get("year")

                # Saga info:
                saga_name = form.cleaned_data.get("saga")
                if saga_name:
                    try:
                        book.saga = Saga.objects.get(name=saga_name)
                    except ObjectDoesNotExist:
                        saga_name = Saga(name=saga_name)
                        saga_name.save()
                        book.saga = saga_name
                    book.index_in_saga = form.cleaned_data.get("index")
                book.save()  # we must save BEFORE we add many-to-many field items (author(s) below)

                # Add author data:
                author_names = [a.strip() for a in form.cleaned_data.get("author", "").split(",")]
                for author_name in author_names:
                    try:
                        author = Author.objects.get(name=author_name)
                    except Author.DoesNotExist:
                        author = Author(name=author_name)
                        author.save()
                    book.authors.add(author)

                return redirect("books:book_detail", book_id=book.id)

    book = Book.objects.get(id=book_id)
    initial = {
        "title": book.title,
        "author": ", ".join(book.list_of_authors),
        "pages": book.pages,
        "year": book.year,
        "saga": book.saga,
        "index": book.index_in_saga,
    }
    form = AddBookForm(initial=initial)

    context = {
        "form": form,
        "book": book,
        "action": "modify",
    }

    return render(request, 'books/add_or_modify_book.html', context)


def start_book(request):
    """View to start reading a book."""

    if request.method == "POST":
        return handle_start_reading_post(request)
    else:
        return handle_start_reading_get(request)


def mark_book_read(request, book_id):
    """Come here with a GET to mark a book read."""

    book = Book.objects.get(pk=book_id)
    book.mark_read()

    return redirect("books:book_detail", book_id=book_id)


def mark_book_owned(request, book_id):
    """Come here with a GET to mark a Book as owned."""

    book = Book.objects.get(pk=book_id)
    book.owned = True
    book.save()

    return redirect("books:book_detail", book_id=book_id)


def author_detail(request, author_id=None):
    """Detail view for an author."""

    author = Author.objects.get(pk=author_id)

    context = {
        "author": author,
    }

    return render(request, "books/author_detail.html", context)


def stats(request, year=None):
    """View with statistics for 'year'."""

    # If no year given, use current:
    if year is None:
        year = timezone.now().year

    state = statistics.State(year)

    pages_per_day = state.pages_per_day
    required_pages_per_day = state.required_pages_per_day

    try:
        ppd_perc = 100. * pages_per_day / (pages_per_day + required_pages_per_day)
    except ZeroDivisionError:
        ppd_perc = 0.0

    total_pages = 15000
    pages_per_book = 600
    perc_total_pages = 100. * state.pages_read / total_pages
    perc_ppb = 100. * state.pages_per_book / pages_per_book

    # Books read bar:
    blue_bar = state.book_percent_read
    if blue_bar >= 100.0:
        blue_bar = 100.0
        red_bar = 0
        green_bar = 0
    elif state.book_superavit > 0:
        red_bar = 0
        green_bar = state.book_superavit_percent
        blue_bar = blue_bar - green_bar
    else:
        red_bar = state.book_deficit_percent
        green_bar = 0

    books_read_bar = {
        "blue_bar": blue_bar,
        "red_bar": red_bar,
        "green_bar": green_bar,
    }

    # Expected books bar:
    if state.expected_books_by_end_of_year > state.GOAL:
        green_bar = 100. * state.expected_books_by_end_of_year / (2. * state.GOAL)
        blue_bar = 0
        red_bar = 0
    else:
        red_bar = 100. * state.expected_books_by_end_of_year / (2. * state.GOAL)
        blue_bar = 50. - red_bar
        green_bar = 0

    expected_books_bar = {
        "blue_bar": blue_bar,
        "red_bar": red_bar,
        "green_bar": green_bar,
    }

    context = {

books/templates/books/add_or_modify_book.html
{% extends "books/base.html" %}
{% load bootstrap4 %}

{% block content %}
{% if action == "add" %}
<div class="banner add-color">Add book</div>
{% endif %}

{% if action == "modify" %}
<div class="banner add-color">Modify '{{book.title}}'</div>
{% endif %}
{% include "books/top_menu.html" %}

<form action="" method="post" class="add-book ml-3">
    {% csrf_token %}
    {% bootstrap_form form layout="vertical" %}

    {% if action == "add" %}
    <input type="submit" class="submit mt-3" name="wished" value="Wished">
    <input type="submit" class="submit" name="ordered" value="Ordered">
    <input type="submit" class="submit" name="acquired" value="Acquired">
    <input type="submit" class="submit" name="reading" value="Reading">
    <a class="btn btn-warning btn-lg ml-3" href="{% url 'books:stats' %}">Cancel</a>
    {% endif %}

    {% if action == "modify" %}
    <input type="submit" class="submit mt-3" name="modify" value="Modify">
    <a class="btn btn-warning btn-lg ml-3" href="{% url 'books:book_detail' book.id %}">Cancel</a>
    {% endif %}
</form>

{% endblock %}

books/templates/books/author_detail.html
{% extends "books/base.html" %}

{% block content %}

<div id="banner">Author: {{author.name}}</div>

<br>

{% include "books/top_menu.html" %}

<br>

<table>
    <tr>
        <th>Books</th>
    </tr>
    {% for book in author.book_set.all %}
    <tr>
        <td style="padding: 5px 20px">
            <a href="{% url 'books:book_detail' book.id %}">{{ book }}</a>
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

books/templates/books/base.html
{% load static %}

<head>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'books/icons/favicon.png' %}"/>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="{% static 'books/js/myjs.js' %}"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>

{% block content %}
{% endblock %}

books/templates/books/bokeh_header.html
<head>
    <link href="https://cdn.pydata.org/bokeh/release/bokeh-0.13.0.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.13.0.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.13.0.min.css" rel="stylesheet" type="text/css">

    <script src="https://cdn.pydata.org/bokeh/release/bokeh-0.13.0.min.js"></script>
    <script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.13.0.min.js"></script>
    <script src="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.13.0.min.js"></script>
</head>

books/templates/books/book_detail.html
{% extends "books/base.html" %}

{% block content %}
{% include "books/top_menu.html" %}

<div class="book-detail-grid mt-1 ml-3" style="width: 800px">
    <div class="two-col-grid-text">Title:</div><div class="two-col-grid-text">{{ book.title }}</div>
    <div class="two-col-grid-text">Author:</div>
    <div class="two-col-grid-text">
        {% for author in book.authors.all %}
        <a href="{% url 'books:author_detail' author.id %}">{{ author }}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </div>
    <div class="two-col-grid-text">Pages:</div><div class="two-col-grid-text">{{ book.pages }}</div>
    <div class="two-col-grid-text">Published:</div><div class="two-col-grid-text">{{ book.year }}</div>

    {% if book.saga %}
    <div class="two-col-grid-text">Saga:</div><div class="two-col-grid-text">{{ book.saga }} #{{book.index_in_saga}}</div>
    {% endif %}
</div>

<a class="btn btn-primary btn-lg mt-3 ml-3" href="{% url 'books:modify_book' book.id %}">Modify</a>
<a class="btn btn-success btn-lg mt-3 ml-2" href="{% url 'books:update_book_progress' book.id %}">Update</a>
{% if not book.owned %}
<a class="btn btn-info btn-lg mt-3 ml-2" href="{% url 'books:mark_book_owned' book.id %}">Mark owned</a>
{% endif %}

{% for plot in plotly_plots %}
<div class="book-progress-plot">
    {{plot|safe}}
</div>
{% endfor %}

{% if plotly_plots %}
<div class="book-detail-grid mt-5 ml-3" style="width: 900px; font-size: 25px">
    <div class="two-col-grid-text">Date</div><div class="two-col-grid-text">Event</div>

    {% for event in book.events %}
    <div class="two-col-grid-text">{{event.when|date:"Y-m-d H:i" }}</div>
    {% if event.page_equivalent == 0 %}
    <div class="two-col-grid-text">
        <div class="progress" style="width: 100%; height: 50px; font-size: 25px;">
            <div class="progress-bar bg-danger ml-0" role="progressbar" style="width: 0%"></div>
        </div>
    </div>
    {% elif event.progress_percent == 100 %}
    <div class="two-col-grid-text">
        <div class="progress" style="width: 100%; height: 50px; font-size: 25px;">
            <div class="progress-bar bg-success ml-0" role="progressbar" style="width: 100%">
                {{event.page_equivalent}}</div>
        </div>
    </div>
    {% else %}
    <div class="two-col-grid-text">
        <div class="progress" style="width: 100%; height: 50px; font-size: 25px;">
            <div class="progress-bar bg-primary pl-2" role="progressbar" style="width: {{event.progress_percent}}%">
                {{event.page_equivalent}}</div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endif %}
{% endblock %}

books/templates/books/header.html
{% load static %}
{% load bootstrap4 %}

<head>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'books/icons/favicon.png' %}"/>
    <script src="{% static 'books/js/myjs.js' %}"></script>
</head>

{% block content %}
{% endblock %}

books/templates/books/index.html
{% extends "books/base.html" %}

{% block content %}

<div class="banner index-color">Index</div>
{% include "books/top_menu.html" %}

<br><br>

{% if currently_reading_books %}
<div class="index-grid" style="width: 800px">
    <div class="two-col-grid-text button-books">Currently reading</div>
    <div class="two-col-grid-text button-books">Pages read</div>
    {% for book in currently_reading_books %}
        <div class="two-col-grid-text"><a href="{% url 'books:book_detail' book.id %}">{{book.title}}</a></div>
        <div class="two-col-grid-number">{{book.pages_read}}</div>
    {% endfor %}
</div>
<br><br>
{% endif %}

{% if currently_ordered_books %}
<div class="index-grid" style="width: 800px">
    <div class="two-col-grid-text button-books">Currently ordered</div>
    <div></div>
    {% for book in currently_ordered_books %}
    <div class="two-col-grid-text"><a href="{% url 'books:book_detail' book.id %}">{{book.title}}</a></div>
    <div></div>
    {% endfor %}
</div>
<br><br>
{% endif %}

<div class="index-grid" style="width: 800px">
    <div class="two-col-grid-text button-books">Already read</div>
    <div class="two-col-grid-text button-books">Date finished</div>
    {% for book in already_read_books %}
        <div class="two-col-grid-text"><a href="{% url 'books:book_detail' book.id %}">{{book.title}}</a></div>
        <div>{{book.date_read|date:"Y-m-d H:i"}}</div>
    {% endfor %}
</div>

{% endblock %}

books/templates/books/sagas.html
{% extends "books/base.html" %}

{% block content %}

<div class="banner sagas-color">Sagas</div>
{% include "books/top_menu.html" %}

<br>

<div class="header">
    {{completed|length}} sagas completed
    <button class="toggle" onclick="mytoggle('show_saga_completed')">[toggle show]</button>
</div>

<div id="show_saga_completed" style="display: none;">
    {% for saga in completed %}
    <div class="saga-head">
        {{saga}} <button class="toggle" onclick="mytoggle('{{saga}}')">[toggle show]</button>
    </div>

    <div class="saga-grid" id="{{saga}}" style="display: none;">
        {% for book in saga.books %}
        <div class="{{book.status}}">
            <a href="{% url 'books:book_detail' book.id %}" style="color: #111111;">#{{book.index_in_saga}} {{book}}</a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>


<div class="header">
    {{owned|length}} sagas owned
    <button class="toggle" onclick="mytoggle('show_saga_owned')">[toggle show]</button>
</div>

<div id="show_saga_owned" style="display: none;">
    {% for saga in owned %}
    <div class="saga-head">
        {{saga}} <button class="toggle" onclick="mytoggle('{{saga}}')">[toggle show]</button>
    </div>

    <div class="saga-grid" id="{{saga}}" style="display: none;">
        {% for book in saga.books %}
        <div class="{{book.status}}">
            <a href="{% url 'books:book_detail' book.id %}" style="color: #111111;">#{{book.index_in_saga}} {{book}}</a>
        </div>
        {% endfor %}
    </div>
{% endfor %}
</div>


<div class="header">
    {{missing|length}} sagas missing one or more books
    <button class="toggle" onclick="mytoggle('show_saga_missing')">[toggle show]</button>
</div>

<div id="show_saga_missing" style="display: none;">
    {% for saga in missing %}
    <div class="saga-head">
        {{saga}} <button class="toggle" onclick="mytoggle('{{saga}}')">[toggle show]</button>
    </div>

    <div class="saga-grid" id="{{saga}}" style="display: none;">
        {% for book in saga.books %}
        <div class="{{book.status}}">
            <a href="{% url 'books:book_detail' book.id %}" style="color: #111111;">#{{book.index_in_saga}} {{book}}</a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

</div>

{% endblock %}

books/templates/books/start_book.html
{% extends "books/base.html" %}

{% block content %}
<div class="banner index-color">Start reading a book</div>
{% include "books/top_menu.html" %}

<form action="{% url 'books:start_book' %}" method="post" class="ml-3">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="submit" value="Submit">
</form>

<div class="saga-grid mt-2 ml-2 mr-2">
    {% for book in matching_books %}
    <div class="{{book.status}}">
        <a href="{% url 'books:update_book_progress' book.id %}" style="color: #111111;">{{book}}</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

books/templates/books/stats.html
{% extends "books/base.html" %}

{% block content %}
<div class="banner stats-color">Statistics</div>
{% include "books/top_menu.html" %}

<div class="stats-book-grid" style="margin-top: 35px; margin-left: 10px; margin-right: 10px;">

    {% for book in currently_reading_books %}
    <div class="progress bg-secondary" style="width: 100%; height: 50px; font-size: 30px; grid-column: span 1;">
        <div class="progress-bar bg-primary pl-3 text-white" role="progressbar" style="width: {{book.percent_read}}%;" aria-valuenow="100"
             aria-valuemin="0" aria-valuemax="200">{{book.title}} ({{book.pages_read}} / {{book.pages}})</div>
    </div>
    <a class="modify-condensed" href="{% url 'books:update_book_progress' book.id %}">Update</a>
    {% endfor %}

    <div class="mt-5 pl-2" style="background-color: white; width: 100%;">
        {{state.books_read|floatformat:1}} / {{state.expected_books_so_far|floatformat:1}} books read
    </div>
    <div class="progress bg-secondary" style="width: 100%; height: 50px; font-size: 30px; grid-column: span 2;">
        <div class="progress-bar" role="progressbar" style="width: {{books_read_bar.blue_bar}}%;"
             aria-valuenow="100" aria-valuemin="0" aria-valuemax="200"></div>
        <div class="progress-bar bg-success" role="progressbar" style="width: {{books_read_bar.green_bar}}%"
             aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
        <div class="progress-bar bg-danger" role="progressbar" style="width: {{books_read_bar.red_bar}}%"
             aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

    <div class="mt-4 pl-2" style="background-color: white; width: 100%;">
        {{state.expected_books_by_end_of_year|floatformat:1}} / {{state.GOAL}} books expected by end of year
    </div>
    <div class="progress bg-secondary" style="width: 100%; height: 50px; font-size: 30px; grid-column: span 2;">
        <div class="progress-bar bg-danger" role="progressbar" style="width: {{expected_books_bar.red_bar}}%"></div>
        <div class="progress-bar" role="progressbar" style="width: {{expected_books_bar.blue_bar}}%;"></div>
        <div class="progress-bar bg-success" role="progressbar" style="width: {{expected_books_bar.green_bar}}%"></div>
    </div>

    <div class="progress bg-secondary mt-5" style="width: 100%; height: 50px; font-size: 30px; grid-column: span 2;">
        {% if pages_per_day.0 > pages_per_day.1 %}
        <div class="progress-bar bg-success" role="progressbar" style="width: {{pages_per_day.2}}%;"
             aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{pages_per_day.0|floatformat:1}} ppd</div>
        <div class="progress-bar bg-secondary" role="progressbar" style="width: {{pages_per_day.3}}%" aria-valuenow="30"
             aria-valuemin="0" aria-valuemax="100">{{pages_per_day.1|floatformat:1}} ppd</div>
        {% else %}
        <div class="progress-bar bg-secondary" role="progressbar" style="width: {{pages_per_day.2}}%;"
             aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{pages_per_day.0|floatformat:1}} ppd</div>
        <div class="progress-bar bg-danger" role="progressbar" style="width: {{pages_per_day.3}}%" aria-valuenow="30"
             aria-valuemin="0" aria-valuemax="100">{{pages_per_day.1|floatformat:1}} ppd</div>
        {% endif %}
    </div>

    <div class="progress bg-secondary" style="width: 100%; height: 50px; font-size: 30px; grid-column: span 2;">
        <div class="progress-bar" role="progressbar" style="width: {{perc_total_pages}}%;" aria-valuenow="100"
             aria-valuemin="0" aria-valuemax="100">{{state.pages_read}} pages read</div>
    </div>

    <div class="progress bg-secondary" style="width: 100%; height: 50px; font-size: 30px; grid-column: span 2;">
        <div class="progress-bar" role="progressbar" style="width: {{perc_ppb}}%;" aria-valuenow="100"
             aria-valuemin="0" aria-valuemax="100">{{state.pages_per_book|floatformat:1}} pages per book</div>
    </div>
</div>
{% endblock %}

books/templates/books/top_menu.html
{% load static %}

<div class="btn-group ml-3 my-3">
    <a class="btn btn-success btn-lg" href="/">Home</a>
</div>

<div class="btn-group ml-3 col-0">
    <a class="btn btn-secondary btn-lg" href="{% url 'books:stats' %}">Stats</a>
    <a class="btn btn-secondary btn-lg" href="{% url 'books:index' %}">Index</a>
    <a class="btn btn-secondary btn-lg" href="{% url 'books:sagas' %}">Sagas</a>
</div>

<div class="btn-group ml-3 col-0">
    <a class="btn btn-primary btn-lg" href="{% url 'books:start_book' %}">Start</a>
    <a class="btn btn-primary btn-lg" href="{% url 'books:add_book' %}">Add</a>
</div>

books/templates/books/update_book_progress.html
{% extends "books/base.html" %}

{% block content %}
{% include "books/top_menu.html" %}

<div class="banner">Modify book: {{book.title}}</div>

<form action="{% url 'books:update_book_progress' book.id %}" method="post" style="margin-left: 10px;">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="submit" value="Submit">
</form>

<a class="btn btn-danger btn-lg ml-3" href="{% url 'books:mark_book_read' book.id %}">Mark read</a>
<a class="btn btn-warning btn-lg ml-3" href="{% url 'books:book_detail' book.id %}">Cancel</a>
{% endblock %}